### ISSUE TITLE
No USDT-Pairs Market Support

### ISSUE THREAD

**Issue by shreyasgp** [bitbns-official/python-bitbns-api#4]
Not able to view orderbook or place orders on USDT pairs(BTCUSDT,XRPUSDT etc), the error is:
{"data":"","status":0,"msg":"coin name not supplied","code":406}

**Comment by tanmesh** [comment]
The issue has been tracked. You can use *bitbnsObj.getSellOrderBook('BTCUSDT')* to view orderbook or place orders on USDT pairs.
